/**
 * Seed script: Updates module descriptions + extends quizzes to 15 questions per module
 * for the Master Claude AI — Zero to Pro course.
 *
 * Usage: npx tsx scripts/seed-claude-quizzes-and-intros.ts
 */

import { createClient } from '@supabase/supabase-js'
import * as path from 'path'
import * as dotenv from 'dotenv'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseUrl || !supabaseKey) {
  console.error('❌  Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const db = createClient(supabaseUrl, supabaseKey)

// ─── Module intro JSON descriptions ──────────────────────────────────────────
const MODULE_INTROS: Record<string, { overview: string; prerequisites: string[]; objectives: string[] }> = {
  'What Is Claude & Why It Matters': {
    overview: "Kick off your Claude AI journey by understanding what Claude is, how Anthropic built it differently, and why it's rapidly becoming the leading AI for serious work.",
    prerequisites: ['Basic familiarity with AI chatbots', 'No coding experience required'],
    objectives: ["Understand what makes Claude different from other LLMs", "Learn Claude's core use cases: coding, writing, research", "Explore Agentic AI and what it means for the future", "Compare Claude to GPT-4 and Gemini at a high level"],
  },
  'The Claude Interface & Core Features': {
    overview: "Explore the Claude.ai web interface end-to-end — from creating and managing conversations to customizing your experience and understanding context windows.",
    prerequisites: ['Have a free Claude.ai account', 'Be comfortable using a web browser'],
    objectives: ['Navigate the Claude.ai web UI confidently', 'Create, rename, search, and delete conversations', 'Understand what the context window is and its limits', 'Enable personalization and style features'],
  },
  'Prompt Engineering for Claude': {
    overview: "Go deep on prompt engineering — the single most important skill for getting exceptional results from Claude. Learn XML tags, chain-of-thought techniques, and few-shot prompting.",
    prerequisites: ['Completed Module 1 (What Is Claude & Why It Matters)', 'Basic understanding of natural language instructions'],
    objectives: ['Write structured prompts using XML tags', 'Apply chain-of-thought prompting for deeper reasoning', 'Use few-shot examples to shape response format', 'Understand role prompting and system prompts'],
  },
  'Claude Artifacts': {
    overview: "Discover Claude Artifacts — the built-in interactive workspace that opens side-by-side to your chat, letting you build, run, and iterate on code, documents, and web pages in real time.",
    prerequisites: ['Familiarity with the Claude.ai interface (Module 2)', 'Some exposure to code or HTML is helpful but not required'],
    objectives: ['Open and navigate the Artifacts panel in Claude.ai', 'Generate interactive HTML/CSS/JS apps inside Artifacts', 'Render SVG graphics and diagrams', 'Iterate on Artifact content using follow-up prompts'],
  },
  'Claude Projects': {
    overview: "Learn to use Claude Projects — a powerful workspace feature that lets you bundle knowledge files, custom instructions, and chat history into a shared context.",
    prerequisites: ['Claude Pro or Team plan (for full Projects access)', 'Understanding of the basic Claude interface'],
    objectives: ['Create and configure a new Claude Project', 'Upload and index documents as project knowledge', 'Write custom system instructions for all project chats', 'Share Projects with team members'],
  },
  'Claude Skills & Connectors': {
    overview: "Extend Claude's capabilities beyond its built-in knowledge using Skills (custom tools) and Connectors (external integrations) — turning Claude into an agent that can interact with real-world data.",
    prerequisites: ['Completed Module 3 (Prompt Engineering)', 'Basic understanding of APIs (helpful but not required)'],
    objectives: ["Understand what Claude's Skills and Connectors are", 'Connect Claude to Google Workspace and other tools', 'Build simple custom Skills for repetitive tasks', 'Safely manage connector permissions and data access'],
  },
  'Claude CoWork': {
    overview: "Use Claude as a real collaborative partner in your day-to-day work using the Claude Desktop App — pair programming, document drafting, multi-step task chains, and more.",
    prerequisites: ['Install the Claude Desktop App on your Mac or Windows machine', 'Basic comfort with terminal commands (for developers)'],
    objectives: ['Install and set up the Claude Desktop App', 'Apply CoWork patterns: pair programming, writing, review', 'Chain multi-step tasks using Claude as a co-pilot', 'Use Claude for meeting notes, summaries, and action items'],
  },
  'Extended Thinking & Research Mode': {
    overview: "Unlock Claude's most powerful reasoning capabilities: Extended Thinking (showing step-by-step thought process) and Research Mode (deep multi-source web search and synthesis).",
    prerequisites: ['Claude Pro plan (required for Extended Thinking)', 'Good understanding of Claude prompting (Module 3)'],
    objectives: ["Enable and use Extended Thinking for hard reasoning tasks", "Read and interpret Claude's thinking trace", 'Use Research Mode for in-depth multi-source research', 'Apply Extended Thinking to advanced code debugging'],
  },
  'Claude Code': {
    overview: "Master Claude Code — Anthropic's official command-line agentic tool that operates directly inside your local development environment to write, edit, test, and ship code.",
    prerequisites: ['Node.js 18+ installed on your machine', 'Basic terminal/CLI experience', 'A Claude Pro or API account'],
    objectives: ['Install and authenticate Claude Code via npm', 'Use the claude command to interact with your local codebase', 'Integrate Claude Code with VS Code', 'Use Claude Code to automate git workflows and testing'],
  },
  'MCP — Model Context Protocol': {
    overview: "Learn the Model Context Protocol (MCP) — the open standard that connects Claude to any data source, tool, or API. Configure MCP servers on Claude Desktop to supercharge your workflows.",
    prerequisites: ['Claude Desktop App installed (Module 7)', 'Basic JSON editing skills', 'Understanding of what APIs and servers are'],
    objectives: ['Understand the MCP architecture: client, server, resources, tools', 'Configure MCP servers in claude_desktop_config.json', 'Connect Claude to a local database via MCP', 'Discover and install community MCP servers from GitHub'],
  },
}

// ─── Quiz questions (15 per module, option_a/b/c/d format) ───────────────────
type Q = { question: string; option_a: string; option_b: string; option_c: string; option_d: string; correct_option: 'a' | 'b' | 'c' | 'd'; explanation: string }
const MODULE_QUIZZES: Record<string, Q[]> = {
  'What Is Claude & Why It Matters': [
    { question: 'Who created Claude?', option_a: 'OpenAI', option_b: 'Google DeepMind', option_c: 'Anthropic', option_d: 'Meta AI', correct_option: 'c', explanation: 'Claude is developed by Anthropic, an AI safety company founded in 2021.' },
    { question: "What is Anthropic's primary design philosophy for Claude?", option_a: 'Speed above all else', option_b: 'Safety and helpfulness', option_c: 'Maximum creativity', option_d: 'Cost-effectiveness', correct_option: 'b', explanation: 'Anthropic builds Claude with a Constitutional AI approach, prioritizing safety, honesty, and helpfulness.' },
    { question: 'What is a key technical advantage Claude has over many competing LLMs?', option_a: 'Built-in image generation', option_b: 'Very large context window (up to 200K tokens)', option_c: 'Faster training speed', option_d: 'Runs locally without internet', correct_option: 'b', explanation: 'Claude 3 models feature industry-leading context windows enabling very long document processing.' },
    { question: 'What does "Agentic AI" mean in the context of Claude?', option_a: 'AI that generates video content', option_b: 'AI that autonomously plans and executes multi-step tasks using tools', option_c: 'AI that can make phone calls', option_d: 'AI that only answers single questions', correct_option: 'b', explanation: 'Agentic AI refers to AI systems that act autonomously, use tools, plan sequences of actions, and accomplish complex goals.' },
    { question: 'Which Claude plan does NOT train on your conversation data by default?', option_a: 'Free plan', option_b: 'Pro plan', option_c: 'Team and Enterprise plans', option_d: 'All plans', correct_option: 'c', explanation: 'Claude Team and Enterprise plans have strict data privacy — conversations are not used for model training by default.' },
    { question: 'What model family is Claude 3.5 Sonnet part of?', option_a: 'Claude 1 family', option_b: 'Claude 2 family', option_c: 'Claude 3 family', option_d: 'Claude 4 family', correct_option: 'c', explanation: 'Claude 3.5 Sonnet is part of the Claude 3 model family (Haiku, Sonnet, Opus tiers).' },
    { question: "What does Claude's Constitutional AI training approach aim to achieve?", option_a: 'Faster training times', option_b: 'A model aligned to principles for safe, helpful, honest behavior', option_c: 'Unlimited output length', option_d: 'Perfect code generation', correct_option: 'b', explanation: 'Constitutional AI is a training technique for making AI follow a defined set of safety and helpfulness principles.' },
    { question: 'Which capability best distinguishes Claude from a basic search engine?', option_a: 'Returning the top 10 links', option_b: 'Synthesizing information, reasoning, and generating novel content', option_c: 'Indexing real-time web pages', option_d: 'Storing bookmarks', correct_option: 'b', explanation: 'Unlike search engines, Claude can reason, synthesize, compose, code, and generate creative outputs.' },
    { question: 'What API do developers use to access Claude programmatically?', option_a: 'Claude Dev API', option_b: 'Anthropic Claude API', option_c: 'Claude Studio API', option_d: 'Claude Connector API', correct_option: 'b', explanation: 'Developers access Claude through the Anthropic Claude API for programmatic access to all Claude models.' },
    { question: "What is one of Claude's strongest capabilities vs other AI models?", option_a: 'Image generation', option_b: 'Long-form document analysis and reasoning', option_c: 'Voice synthesis', option_d: 'Real-time stock data lookup', correct_option: 'b', explanation: 'Claude excels at long document analysis, reasoning, writing, and instruction following.' },
    { question: 'Which task is Claude especially well-suited for?', option_a: 'Rendering 3D graphics', option_b: 'Writing, debugging, and explaining code', option_c: 'Video editing automation', option_d: 'Native OS command execution', correct_option: 'b', explanation: 'Claude has strong coding capabilities — writing, debugging, explaining, and reviewing code across dozens of languages.' },
    { question: "What does Claude's token count limit relate to?", option_a: 'Files you can upload per day', option_b: 'Total input + output text Claude can process in one session', option_c: 'How fast Claude responds', option_d: 'Free messages per month', correct_option: 'b', explanation: 'Tokens are the text units Claude processes. The context window limit determines how much input+output Claude can handle.' },
    { question: 'What is the primary difference between Claude Haiku, Sonnet, and Opus?', option_a: 'Their output language', option_b: 'Speed and capability trade-offs — Haiku is fastest/cheapest, Opus most capable', option_c: 'The file formats they can read', option_d: 'Their ability to generate images', correct_option: 'b', explanation: 'Claude tiers represent speed/capability trade-offs: Haiku (fast/cheap), Sonnet (balanced), Opus (most powerful).' },
    { question: "Who funds Anthropic's AI safety research?", option_a: 'Only the U.S. Government', option_b: 'Private investors and VCs including Google and Amazon', option_c: 'Only Amazon', option_d: 'Open source community donations', correct_option: 'b', explanation: 'Anthropic has received funding from Google, Amazon, and various venture capital firms.' },
    { question: 'What does Claude use to handle very long documents?', option_a: 'An external hard drive', option_b: "The context window — all provided text is loaded into the model's active memory", option_c: 'Cloud storage accounts', option_d: 'A vector database by default', correct_option: 'b', explanation: "Claude's context window holds all conversation text in active memory. Longer windows (200K tokens) allow processing of entire books." },
  ],
  'The Claude Interface & Core Features': [
    { question: 'Where do you access the Claude.ai web interface?', option_a: 'claude.app', option_b: 'claude.ai', option_c: 'anthropic.chat', option_d: 'ai.claude.com', correct_option: 'b', explanation: 'The official Claude web interface is accessible at claude.ai.' },
    { question: 'How does Claude.ai store your previous conversations?', option_a: 'Permanently deleted after 24 hours', option_b: 'Saved in the left sidebar for easy access', option_c: 'Emailed to you as a PDF', option_d: 'Stored only in browser cache', correct_option: 'b', explanation: 'Claude.ai automatically saves all conversations in the left sidebar where you can search, rename, and continue them.' },
    { question: "What is the 'context window' in Claude's web chat?", option_a: 'The browser window size', option_b: 'The maximum amount of text Claude can process in a single conversation session', option_c: 'The number of files you can upload', option_d: 'The chat history visible on screen', correct_option: 'b', explanation: 'The context window is the total token capacity Claude holds in active memory during a conversation, including all messages.' },
    { question: 'How can you upload a file to Claude.ai for analysis?', option_a: 'By emailing it to support@anthropic.com', option_b: 'Using the attachment icon or dragging files into the chat box', option_c: 'Only by providing a URL link', option_d: 'Files cannot be uploaded to Claude.ai', correct_option: 'b', explanation: 'Claude.ai supports file uploads via the attachment button or drag-and-drop into the chat interface.' },
    { question: 'What file types can you upload to Claude.ai?', option_a: 'Only .txt files', option_b: 'PDFs, Word docs, images, code files, CSV, and more', option_c: 'Only image files (PNG/JPG)', option_d: 'Only Excel spreadsheets', correct_option: 'b', explanation: 'Claude.ai accepts PDFs, Word documents, images, code files, text files, and CSV files.' },
    { question: 'What happens when you start a new chat in Claude.ai?', option_a: 'Claude remembers all your previous conversations by default', option_b: 'A fresh context is created with no memory of past chats (unless Projects are used)', option_c: 'Your account is logged out', option_d: 'All previous chats are deleted', correct_option: 'b', explanation: 'Each new Claude chat starts with an empty context window — no memory of past conversations unless you use Projects.' },
    { question: 'How do you edit or delete a past conversation in Claude.ai?', option_a: 'You cannot edit past conversations', option_b: 'By hovering over the conversation in the sidebar for options like rename and delete', option_c: 'By contacting Anthropic support', option_d: 'Only administrators can delete conversations', correct_option: 'b', explanation: 'Hovering over a conversation in the sidebar reveals options to rename, share, or delete it.' },
    { question: "What is the purpose of Claude's 'Custom Instructions' settings?", option_a: "Set Claude's response language", option_b: 'Define your background, role, and preferences so Claude tailors all responses to you', option_c: 'Unlock extra file upload space', option_d: 'Schedule when Claude responds to you', correct_option: 'b', explanation: "Claude's custom instructions let you tell Claude who you are, your preferred tone, and what you care about — persisting across all chats." },
    { question: "What does 'Voice' mode in Claude.ai allow you to do?", option_a: 'Listen to music via Claude', option_b: 'Interact with Claude using spoken audio input and receive voice output', option_c: 'Record video meetings', option_d: 'Run Claude on a smart speaker', correct_option: 'b', explanation: "Claude's voice mode enables hands-free, spoken conversation with Claude, useful for accessibility and on-the-go use." },
    { question: "What is Claude.ai's Artifacts panel?", option_a: 'A tab showing your billing history', option_b: 'A side panel that displays generated code, documents, or interactive previews alongside the chat', option_c: 'A place to store uploaded files', option_d: 'A reading list of article recommendations', correct_option: 'b', explanation: 'Artifacts is a split-screen workspace within Claude.ai that shows live previews of code, SVGs, documents, and other content Claude generates.' },
    { question: 'How can you share a Claude.ai conversation with someone else?', option_a: 'You cannot share conversations', option_b: 'By using the Share button to generate a public link to the conversation', option_c: 'By copying and pasting all the text manually', option_d: 'By downloading the conversation as a video', correct_option: 'b', explanation: 'Claude.ai provides a Share button that generates a shareable URL giving view access to a conversation.' },
    { question: 'What is the approximate maximum file size limit for uploads in Claude.ai?', option_a: '1 MB', option_b: '5 MB', option_c: '10 MB per file, ~32 MB total per conversation', option_d: '1 GB', correct_option: 'c', explanation: 'Claude.ai supports file uploads up to approximately 10 MB per file with a combined limit per conversation session.' },
    { question: "What does Claude's Styles feature let you configure?", option_a: 'The visual color theme of the interface', option_b: "Claude's response tone and format — such as concise, formal, or educational", option_c: 'Your font preferences', option_d: 'The chat bubble color', correct_option: 'b', explanation: "Claude's Styles feature lets you save response format preferences (concise vs. detailed, formal vs. casual) that apply to all chats." },
    { question: 'How do you search through your past conversations in Claude.ai?', option_a: 'You cannot search past conversations', option_b: 'Using the search bar at the top of the conversation sidebar', option_c: 'Only by scrolling through the entire list manually', option_d: 'By downloading all your conversations as a file', correct_option: 'b', explanation: 'Claude.ai provides a search bar in the sidebar that lets you quickly find past conversations by keyword.' },
    { question: 'What is the difference between a Claude.ai free account and a Pro account?', option_a: 'Free accounts can only send 1 message per day', option_b: 'Pro accounts get higher limits, more powerful models, Projects, and priority access', option_c: 'Free accounts cannot upload files', option_d: 'There is no difference', correct_option: 'b', explanation: 'Claude Pro provides significantly higher usage limits, access to the latest models, Projects feature, and priority access during peak hours.' },
  ],
  'Prompt Engineering for Claude': [
    { question: 'Why does Anthropic recommend using XML tags in Claude prompts?', option_a: 'They are required for Claude to understand any prompt', option_b: 'They help Claude clearly distinguish separate sections for better compliance', option_c: 'XML tags give Claude extra processing speed', option_d: "They are needed to unlock Claude's Pro features", correct_option: 'b', explanation: 'XML tags like <instructions>, <context>, and <examples> give Claude a clear semantic structure for complex multi-part prompts.' },
    { question: 'What is "few-shot prompting"?', option_a: 'Asking Claude very short questions', option_b: 'Providing 2-5 examples of desired input-output format so Claude can match the pattern', option_c: 'Using Claude for 3 messages then stopping', option_d: 'A type of image generation prompt', correct_option: 'b', explanation: 'Few-shot prompting gives Claude 2-5 demonstration examples, allowing it to infer the desired format and style.' },
    { question: 'What is "chain-of-thought prompting"?', option_a: 'Chaining multiple Claude accounts together', option_b: 'Asking Claude to write out its step-by-step reasoning before arriving at the final answer', option_c: 'Connecting Claude to an external API', option_d: 'A technique for making Claude respond faster', correct_option: 'b', explanation: 'Chain-of-thought prompting instructs Claude to reason step-by-step, improving accuracy on complex math, logic, and coding tasks.' },
    { question: 'Which XML tag is most commonly used to separate task instructions from input data?', option_a: '<query> for instructions, <answer> for data', option_b: '<instructions> for task description, <document> or <data> for the input', option_c: '<prompt> for instructions, <input> for data', option_d: 'XML tags cannot separate instructions from data', correct_option: 'b', explanation: 'Using <instructions> for the task and <document>/<data> for content helps Claude treat them separately, improving compliance.' },
    { question: "What is a 'system prompt' in Claude's API context?", option_a: 'The first message Claude sends', option_b: "A special pre-conversation instruction that sets Claude's role, constraints, and behavior for all subsequent messages", option_c: 'A debug mode message', option_d: 'The prompt Claude uses to train itself', correct_option: 'b', explanation: "System prompts are hidden instructions passed at the start of a conversation (via the API) to define Claude's persona and rules for the entire session." },
    { question: 'What does "role prompting" mean?', option_a: 'Assigning Claude a specific user account', option_b: 'Telling Claude to act as a specific expert persona (e.g., "You are a senior software engineer") to shape its responses', option_c: 'Having Claude play a video game character', option_d: 'Restricting Claude to specific topics only', correct_option: 'b', explanation: 'Role prompting assigns Claude an expert identity, which often improves the quality and relevance of responses.' },
    { question: "How should you structure a complex prompt to maximize Claude's accuracy?", option_a: 'Write everything in a single long sentence', option_b: 'Use separate XML tags for each component: role, context, task, format, and examples', option_c: 'Use bullet points only', option_d: 'Keep all prompts under 50 words', correct_option: 'b', explanation: 'Separating prompt sections with XML tags gives Claude a clear structure to parse each component correctly.' },
    { question: "What is Claude's <scratchpad> technique used for?", option_a: 'Saving drafts of your prompts', option_b: 'Instructing Claude to think through the problem privately before writing its final answer', option_c: 'Uploading scratch files', option_d: 'A specific Anthropic feature for project notes', correct_option: 'b', explanation: 'Asking Claude to use a <scratchpad> gives it computational space to reason before committing to an answer, improving accuracy.' },
    { question: 'What is "prompt chaining" in Claude?', option_a: 'Locking a prompt so it cannot be changed', option_b: 'Breaking a complex task into sequential sub-tasks where each Claude output becomes the input for the next prompt', option_c: 'Connecting two Claude accounts', option_d: "A way to extend Claude's memory", correct_option: 'b', explanation: 'Prompt chaining decomposes complex workflows into sub-tasks, improving reliability by letting Claude focus on one step at a time.' },
    { question: "What does 'output formatting' mean in the context of prompting Claude?", option_a: "Changing the font on Claude's interface", option_b: "Explicitly specifying the desired structure of Claude's response (e.g., JSON, markdown, numbered list, table)", option_c: 'Formatting the upload files', option_d: "Setting Claude's response speed", correct_option: 'b', explanation: "Telling Claude to respond in a specific format (JSON, bullet list, table) dramatically improves usability in programmatic contexts." },
    { question: 'How do you minimize Claude hallucinating (making things up)?', option_a: 'Ask Claude to answer faster', option_b: "Tell Claude explicitly: 'If you don't know, say so. Do not guess.' and provide authoritative context in the prompt", option_c: 'Use shorter prompts', option_d: 'Use the free Claude tier', correct_option: 'b', explanation: 'Instructing Claude to express uncertainty and providing factual grounding in the prompt significantly reduces hallucinations.' },
    { question: "What is the best way to get Claude to write in your company's brand tone?", option_a: 'Hope Claude guesses correctly', option_b: 'Include examples of on-brand writing inside <examples> tags and describe the tone explicitly', option_c: 'Use a single adjective like "professional"', option_d: 'Upload your logo image', correct_option: 'b', explanation: 'Providing 2-3 brand-aligned examples with explicit tone descriptions helps Claude internalize and replicate your brand voice accurately.' },
    { question: 'What is a "negative instruction" in prompt engineering?', option_a: 'A prompt that insults Claude', option_b: 'An explicit instruction about what Claude should NOT do (e.g., "Do not use bullet points")', option_c: 'A prompt written in a foreign language', option_d: 'An API error code', correct_option: 'b', explanation: 'Negative instructions tell Claude to avoid specific behaviors or formats — they are often more effective than hoping Claude avoids them by default.' },
    { question: 'What does "zero-shot prompting" mean?', option_a: 'Sending zero prompts to Claude', option_b: 'Asking Claude to complete a task without providing any examples, relying entirely on its pre-trained knowledge', option_c: 'A free tier limitation', option_d: 'Giving Claude zero context about the task', correct_option: 'b', explanation: 'Zero-shot prompting means asking Claude to perform a task with instructions only — no examples. It works well for straightforward tasks.' },
    { question: 'When should you use few-shot prompting instead of zero-shot?', option_a: 'Always use zero-shot', option_b: 'When Claude needs to match a specific format, style, or output pattern that is hard to describe in words alone', option_c: 'When sending very long documents', option_d: 'Only when using the Claude API', correct_option: 'b', explanation: 'Few-shot prompting shines when the desired output format or style is nuanced — showing is more effective than telling in these cases.' },
  ],
  'Claude Artifacts': [
    { question: 'What is a Claude Artifact?', option_a: 'An error message from Claude', option_b: 'A standalone piece of content (code, document, SVG, web page) generated by Claude that appears in a dedicated side panel', option_c: 'A Claude Pro-only feature for uploading files', option_d: 'A plugin for VS Code', correct_option: 'b', explanation: 'Artifacts are self-contained outputs that Claude displays in a side panel, separate from the chat, for easy interaction.' },
    { question: 'Where does the Artifacts panel appear in Claude.ai?', option_a: 'In a pop-up overlay covering the main chat', option_b: 'As a side-by-side panel on the right of the chat interface', option_c: 'In a separate browser tab', option_d: 'Below the chat input box', correct_option: 'b', explanation: 'The Artifacts panel opens to the right of the conversation, providing a split-screen view.' },
    { question: 'What triggers Claude to generate an Artifact instead of inline text?', option_a: 'Any response longer than 100 words', option_b: 'Content that is standalone and reusable — like a complete web app, full document, or SVG', option_c: 'All code responses automatically', option_d: 'Only Pro plan users can trigger Artifacts', correct_option: 'b', explanation: 'Claude generates Artifacts for content meant to be a standalone deliverable — complete apps, formatted docs, SVGs.' },
    { question: 'Can Claude render interactive HTML and JavaScript in Artifacts?', option_a: 'No, only static text is supported', option_b: 'Yes, Claude can render fully interactive HTML/CSS/JS previews and even React components inside Artifacts', option_c: 'Only CSS is supported, not JavaScript', option_d: 'Interactive previews require a paid Anthropic hosting plan', correct_option: 'b', explanation: 'Artifacts supports live rendering of HTML, CSS, JavaScript, and React code — working web apps directly in Claude.ai.' },
    { question: 'How do you iterate on a Claude Artifact?', option_a: 'Download it, edit it locally, and re-upload', option_b: 'Ask Claude in the chat to modify specific aspects of the Artifact in natural language', option_c: 'You cannot edit Artifacts after they are created', option_d: 'By using a separate code editor plugin', correct_option: 'b', explanation: 'Simply describe changes in natural language to Claude, and it will update the Artifact in-place.' },
    { question: "What is an 'SVG Artifact' in Claude.ai?", option_a: 'A compressed image file', option_b: 'A scalable vector graphic generated by Claude that renders as a visual image in the Artifacts panel', option_c: 'A sound visualization graph', option_d: 'An error visualization', correct_option: 'b', explanation: 'Claude can generate SVG (Scalable Vector Graphics) code that renders as actual visual graphics inside the Artifacts panel.' },
    { question: 'Which of these is a valid use case for Claude Artifacts?', option_a: 'Playing video games', option_b: 'Building a working calculator web app', option_c: 'Ordering food delivery', option_d: 'Controlling smart home devices', correct_option: 'b', explanation: 'Claude can build complete interactive web applications — like calculators, to-do apps, and dashboards — that run live inside Artifacts.' },
    { question: 'Can you share an Artifact with someone who does not have a Claude account?', option_a: 'No, Artifacts are strictly private', option_b: 'Yes, you can publish an Artifact to get a shareable URL that anyone can view in their browser', option_c: 'Only Pro users can share Artifacts', option_d: 'Artifacts can only be shared as email attachments', correct_option: 'b', explanation: 'Claude.ai lets you publish Artifacts to a shareable public URL without requiring a Claude account.' },
    { question: 'What document formats can Claude produce as Artifacts?', option_a: 'Only HTML', option_b: 'Markdown, plain text, HTML, React, and SVG', option_c: 'Only PDF and Word', option_d: 'Only JSON data files', correct_option: 'b', explanation: 'Claude supports multiple Artifact types: Markdown documents, plain text, HTML web pages, React components, and SVG graphics.' },
    { question: 'How does Claude handle Artifact versioning?', option_a: 'There is no version history', option_b: 'Artifacts maintain a revision history within the conversation, letting you browse and restore previous versions', option_c: 'Versions are saved as new chat messages', option_d: 'Versioning requires a GitHub integration', correct_option: 'b', explanation: 'Each time Claude updates an Artifact, the previous version is retained in a version history accessible from the Artifact panel header.' },
    { question: "What is a 'React Artifact' in Claude.ai?", option_a: 'A history of reactions (likes) on a message', option_b: 'A React.js component that Claude generates and renders as a live interactive preview in the Artifacts panel', option_c: 'A Claude feature for reacting to code errors', option_d: 'An animation library integration', correct_option: 'b', explanation: 'Claude can write React components that execute as live, interactive previews inside Artifacts — complete with state and event handlers.' },
    { question: "What happens if you ask Claude to 'run' code in an Artifact?", option_a: "Claude executes the code on Anthropic's server", option_b: 'For HTML/JS/React Artifacts, the code is rendered and executed in the browser sandbox within the Artifacts panel', option_c: 'Code cannot run in Claude.ai Artifacts', option_d: 'Claude sends the code to AWS Lambda for execution', correct_option: 'b', explanation: 'Front-end code (HTML/JS/CSS/React) in Artifacts runs directly in the browser in a secure sandbox within Claude.ai.' },
    { question: "What is the main benefit of Claude Artifacts over Claude's inline code blocks?", option_a: 'Inline code blocks are always better', option_b: 'Artifacts provide a live preview and editing experience — you can actually see and interact with the output, not just read the code', option_c: 'Artifacts only work for very short code snippets', option_d: 'There is no functional difference', correct_option: 'b', explanation: 'While inline code shows text, Artifacts render the actual output — giving you a functional demo, not just source code to copy.' },
    { question: 'Can you copy the code from an Artifact to use it elsewhere?', option_a: 'No, Artifacts are locked inside Claude.ai', option_b: 'Yes, there is a copy button in the Artifact panel to copy all the source code', option_c: 'Only Pro users can copy Artifact code', option_d: 'Copying requires a special export subscription', correct_option: 'b', explanation: 'The Artifacts panel includes a copy button that lets you copy the full source code for use in your own editor or deployment.' },
    { question: 'What kind of data visualizations can Claude create as an Artifact?', option_a: 'Only bar charts', option_b: 'Interactive charts using React + charting libraries, or SVG-based static visualizations', option_c: 'No data visualizations are supported', option_d: 'Only spreadsheet tables', correct_option: 'b', explanation: 'Claude can create interactive React-based charts using Recharts, Chart.js, or plain SVG, rendered live in the Artifacts panel.' },
  ],
  'Claude Projects': [
    { question: 'What is a Claude Project?', option_a: 'A bug report you file with Anthropic', option_b: 'A dedicated workspace that bundles custom instructions, uploaded knowledge files, and conversation history into a persistent shared context', option_c: 'A scheduled task Claude runs automatically', option_d: 'A plugin marketplace for Claude', correct_option: 'b', explanation: 'Projects in Claude.ai create persistent, customized workspaces where all chats share a common system prompt, knowledge files, and history.' },
    { question: 'What Claude plan is required to use Projects?', option_a: 'Free plan (all users can use Projects)', option_b: 'Claude Pro, Team, or Enterprise plans', option_c: 'Only the Enterprise plan', option_d: 'Any plan that has the Artifacts feature', correct_option: 'b', explanation: 'Projects are available on Claude Pro, Team, and Enterprise plans — not on the free tier.' },
    { question: "What are 'Custom Instructions' in a Claude Project?", option_a: 'Step-by-step setup instructions for the Claude app', option_b: "A system-level prompt that defines Claude's behavior, tone, and rules for every conversation inside that Project", option_c: 'A list of keyboard shortcuts', option_d: 'Settings for uploading files to the Project', correct_option: 'b', explanation: "Custom Instructions in a Project act as a persistent system prompt — every conversation in the Project inherits these rules and behaviors." },
    { question: "What types of files can you add to a Claude Project's knowledge base?", option_a: 'Only image files', option_b: 'PDFs, text files, code files, Word documents, and other supported file formats', option_c: 'Only ZIP archives', option_d: 'Video files (.mp4)', correct_option: 'b', explanation: 'Projects support a wide range of document types — PDFs, text, code files, Word docs — which Claude can reference across all conversations.' },
    { question: 'How does a Claude Project maintain context across multiple conversations?', option_a: 'Claude memorizes individual user messages across sessions', option_b: 'Through the shared knowledge files and custom instructions that are loaded into every conversation in the Project', option_c: 'By storing conversation history in your browser', option_d: 'Projects do not maintain context across conversations', correct_option: 'b', explanation: 'The knowledge files and custom instructions you configure are automatically loaded into every new chat within the Project.' },
    { question: 'What is a good use case for Claude Projects?', option_a: 'Watching YouTube videos through Claude', option_b: 'Managing a codebase documentation project — uploading code files so Claude always has context when answering dev questions', option_c: 'Ordering items via Claude', option_d: 'Running machine learning model training', correct_option: 'b', explanation: 'Projects shine for ongoing work where Claude needs consistent context — such as a codebase, brand guidelines, research notes, or legal documents.' },
    { question: 'How do you share a Claude Project with a teammate?', option_a: 'You cannot share Projects', option_b: 'On Claude Team/Enterprise plans, you can add teammates to the Project so they can access the same knowledge and custom instructions', option_c: 'By exporting the Project as a JSON file', option_d: 'By sending a link to the custom instructions text', correct_option: 'b', explanation: "On Team and Enterprise plans, Projects can be shared with teammates, giving them access to the Project's knowledge base and custom instructions." },
    { question: "What is the knowledge file size limit for a Claude Project?", option_a: '100 KB total', option_b: '10 MB per file, up to about 200K tokens total knowledge base size', option_c: '10 GB total', option_d: 'There is no size limit', correct_option: 'b', explanation: 'Claude Projects have a knowledge base that supports file uploads with a combined token limit for the active knowledge context.' },
    { question: 'How does Claude use the knowledge files inside a Project when you ask a question?', option_a: 'It only reads the most recently uploaded file', option_b: 'Claude loads relevant knowledge from the uploaded files into the conversation context to inform its answers', option_c: 'It searches the internet using the file names as queries', option_d: 'Knowledge files are never automatically loaded', correct_option: 'b', explanation: 'Claude references the uploaded knowledge files within the Project context, using them to answer questions accurately based on your specific documents.' },
    { question: 'Can you have multiple Projects in Claude.ai?', option_a: 'No, only one Project per account', option_b: 'Yes, you can create unlimited Projects, each with their own knowledge and custom instructions', option_c: 'Only 2 Projects per Pro account', option_d: 'Only Team accounts can have more than 1 Project', correct_option: 'b', explanation: 'You can create multiple Projects in Claude.ai — each is a separate workspace with its own custom instructions and uploaded knowledge.' },
    { question: 'What is the main advantage of using Claude Projects over starting fresh conversations?', option_a: 'Projects are faster to load', option_b: 'Projects eliminate the need to re-paste context (code, guidelines, documents) in every new conversation', option_c: 'Projects use a different, more powerful AI model', option_d: 'Projects are available offline', correct_option: 'b', explanation: 'Projects save you from repeatedly providing the same background context — your knowledge files and instructions are automatically available in every chat.' },
    { question: "What is a 'Project prompt' or 'Project instructions' used for?", option_a: 'Generating images for the Project', option_b: "Defining Claude's persona, communication style, and behavioral rules that apply consistently to all chats in the Project", option_c: 'Setting the Project name and description', option_d: 'Configuring the file storage location', correct_option: 'b', explanation: 'Project instructions set the foundational behavior for Claude within that project — tone, format preferences, role, constraints.' },
    { question: 'How do Claude Projects handle updates to knowledge files?', option_a: 'Old files must be manually deleted before adding new ones', option_b: 'You can add, remove, or update files at any time, and future conversations will use the updated knowledge', option_c: 'Files cannot be updated once uploaded', option_d: 'Updates only take effect after 24 hours', correct_option: 'b', explanation: 'Knowledge files in a Project can be updated at any time, and new conversations will immediately benefit from the latest versions.' },
    { question: 'Why might a business use Claude Projects instead of individual chats?', option_a: 'Individual chats are more powerful', option_b: 'Projects enable consistent, brand-aligned AI responses across a team — with shared knowledge and instructions', option_c: 'Projects are cheaper than individual chats', option_d: 'Projects allow voice-only interaction', correct_option: 'b', explanation: 'Businesses use Projects to standardize AI behavior across teams — ensuring everyone works with the same context, tone, and knowledge base.' },
    { question: "Can you control Claude's memory of past conversations inside a Project?", option_a: 'Claude automatically remembers everything forever in a Project', option_b: 'By default each conversation is separate; uploaded files provide the persistent knowledge, not conversation history', option_c: 'You can enable a special memory module only in Enterprise', option_d: 'Claude has perfect recall of all Project conversations', correct_option: 'b', explanation: "Within a Project, conversation history is not automatically shared across sessions. The persistent layer is knowledge files and custom instructions, not chat logs." },
  ],
  'Claude Skills & Connectors': [
    { question: "What is a 'Connector' in Claude.ai?", option_a: 'A USB-C port for your computer', option_b: 'An integration that connects Claude to external tools and services so it can use real-time data', option_c: 'A networking cable', option_d: 'A Claude CLI command', correct_option: 'b', explanation: 'Connectors in Claude.ai link the AI to external platforms and APIs, allowing Claude to fetch live data and interact with business tools.' },
    { question: 'Which external tool does Claude.ai currently support as a built-in Connector?', option_a: 'Twitter/X', option_b: 'Google Workspace (Drive, Docs, Gmail)', option_c: 'Netflix', option_d: 'Spotify', correct_option: 'b', explanation: 'Claude.ai supports Google Workspace as a native Connector, allowing Claude to read and reference your Drive files, Docs, and emails.' },
    { question: "What is the difference between Claude's built-in Connectors and MCP servers?", option_a: 'There is no difference', option_b: "Connectors are pre-built integrations in Claude.ai's UI; MCP servers are custom protocol-based integrations configured by developers in Claude Desktop", option_c: 'Connectors are only for Pro users; MCP is only for free users', option_d: 'MCP stands for Main Connector Protocol', correct_option: 'b', explanation: 'Connectors are managed integrations in Claude.ai; MCP (Model Context Protocol) servers are developer-configured, custom tool integrations for Claude Desktop App.' },
    { question: "What is a 'Skill' in the context of Claude AI?", option_a: "A speed rating for how fast Claude responds", option_b: 'A custom capability or tool configured to extend what Claude can do — like running a specific search or calling an API', option_c: 'A keyboard shortcut', option_d: 'A Claude plan upgrade', correct_option: 'b', explanation: "Skills are modular extensions of Claude's capabilities — either via built-in tools (web search, code execution) or custom integrations." },
    { question: "Which built-in Skill does Claude have access to in Claude.ai's standard interface?", option_a: 'Stock trading', option_b: "Web search (via Claude's built-in search integration)", option_c: 'Email sending', option_d: 'Social media posting', correct_option: 'b', explanation: "Claude.ai includes a built-in web search capability that lets Claude retrieve current information from the internet during a conversation." },
    { question: 'What happens when you connect Claude to Google Drive via a Connector?', option_a: 'Claude gains the ability to delete all your Google Drive files', option_b: 'Claude can read and reference the content of your Google Drive documents when answering questions', option_c: 'Your Google Drive is synced locally to Claude', option_d: 'Claude automatically backs up all your files', correct_option: 'b', explanation: 'With the Google Drive Connector, Claude can read your documents and use their content to answer questions and provide contextual help.' },
    { question: 'How do you enable a Connector in Claude.ai?', option_a: 'By writing a custom Python script', option_b: 'Through the Claude.ai settings panel under the Integrations or Connectors section', option_c: 'By emailing Anthropic support', option_d: 'Connectors are enabled automatically for all accounts', correct_option: 'b', explanation: "Connectors are enabled through the Claude.ai interface settings, where you authorize Claude to access specific third-party services." },
    { question: 'What security concern should you be aware of when enabling Connectors?', option_a: 'Connectors can access your credit card', option_b: 'Connectors may have access to sensitive data in your connected tools — review permissions carefully before enabling', option_c: 'Connectors automatically share data with competitors', option_d: 'Connectors change your account password', correct_option: 'b', explanation: 'When enabling Connectors, review what data permissions you are granting — some connectors can read emails, documents, or databases with sensitive information.' },
    { question: "What is a 'tool use' or 'function calling' capability in Claude's API?", option_a: "A marketing term for Claude's writing abilities", option_b: 'A feature that allows developers to define custom functions Claude can call during a conversation to retrieve data or take actions', option_c: 'A shortcut for running Claude commands', option_d: 'An advanced option for Claude to use terminal commands', correct_option: 'b', explanation: 'Tool use (function calling) in the Claude API lets developers define custom functions Claude can call — enabling it to query databases, hit APIs, or run code as part of a response.' },
    { question: "Why is Claude's ability to use external tools important for businesses?", option_a: "It makes Claude's text prettier", option_b: 'It turns Claude from a static knowledge model into a dynamic agent that can take real-world actions and retrieve live data', option_c: 'It reduces API costs', option_d: 'It allows Claude to work offline', correct_option: 'b', explanation: "Tool use transforms Claude into an active agent — capable of pulling live CRM data, filing tickets, updating databases, or calling APIs as part of a workflow." },
    { question: "What is the 'Zapier' or 'Make' integration approach to connecting Claude to other tools?", option_a: 'Running Claude on a Raspberry Pi', option_b: 'Using automation platforms to create workflows between Claude and 5,000+ other apps without writing code', option_c: 'A type of Claude API authentication method', option_d: 'A data backup strategy for Claude Projects', correct_option: 'b', explanation: 'Platforms like Zapier and Make allow no-code/low-code connections between Claude and thousands of apps — triggering Claude responses, emails, spreadsheet updates, and more.' },
    { question: 'What is required to add a Connector in Claude.ai?', option_a: 'Root administrator access to your company servers', option_b: "Authorizing Claude to access the connected tool via OAuth or API keys, and having the appropriate Claude plan", option_c: "Purchasing a separate 'Connector' subscription from Anthropic", option_d: 'Writing JavaScript code for the integration', correct_option: 'b', explanation: "Adding a Connector requires you to authorize Claude through the service's OAuth flow or provide an API key." },
    { question: "What benefit does connecting Claude to your company's knowledge base via a Connector provide?", option_a: 'Claude can delete outdated documents automatically', option_b: "Claude can search and retrieve answers directly from your company's internal documentation without manual copying", option_c: 'Claude replaces your knowledge base software', option_d: 'It reduces the number of employees needed', correct_option: 'b', explanation: 'A knowledge base Connector lets Claude pull company-specific information on demand, acting as an intelligent, context-aware company assistant.' },
    { question: "What does a 'web search' Skill allow Claude to do that it cannot do by default?", option_a: 'Access your local files', option_b: 'Retrieve up-to-date information from the internet that post-dates its training cutoff', option_c: 'Generate images from search results', option_d: 'Send emails based on search queries', correct_option: 'b', explanation: 'The web search skill allows Claude to access current information beyond its training data cutoff — crucial for news, current events, and latest documentation.' },
    { question: 'What is the recommended approach for testing a new Connector or Skill integration?', option_a: 'Deploy it directly to production immediately', option_b: 'Test with sample, non-sensitive data first to verify accuracy, scope of access, and correct behavior', option_c: 'Ask Anthropic to validate it', option_d: 'Connectors cannot be tested before deployment', correct_option: 'b', explanation: "Testing with sample data lets you verify the Connector returns the right data and Claude interprets it correctly before using it with sensitive information." },
  ],
  'Claude CoWork': [
    { question: "What is 'Claude CoWork' describing?", option_a: 'A shared physical co-working space with Anthropic employees', option_b: 'Using Claude as an interactive, real-time collaborative partner integrated into your daily work and development workflow', option_c: 'A feature for two Claude accounts to chat together', option_d: 'A video call feature inside Claude.ai', correct_option: 'b', explanation: 'CoWork describes the practice of using Claude as an active collaborator — pair programmer, writing partner, researcher — deeply integrated into your daily workflow.' },
    { question: 'What does the Claude Desktop App add that the web interface does not have?', option_a: 'A bigger chat box', option_b: 'Native OS integration with local file system access, system-level tool access, and the ability to run MCP servers', option_c: 'Better internet speeds', option_d: 'A built-in code compiler', correct_option: 'b', explanation: 'The Claude Desktop App integrates with your operating system, enabling features like local file access, system-level tool use, and MCP server connections.' },
    { question: 'What platform is Claude Desktop App available on?', option_a: 'Linux only', option_b: 'macOS and Windows', option_c: 'iOS and Android only', option_d: 'All platforms including Linux', correct_option: 'b', explanation: 'The Claude Desktop App is available for macOS and Windows.' },
    { question: 'In a "pair programming" CoWork session with Claude, what is your role?', option_a: "Only reading Claude's output", option_b: "Guiding the problem-solving session, reviewing Claude's code suggestions, providing feedback, and directing next steps", option_c: 'Only running the terminal commands', option_d: 'Watching Claude write all the code autonomously', correct_option: 'b', explanation: 'In pair programming, you act as the navigator — setting direction, reviewing output, catching errors, and steering the problem-solving process.' },
    { question: 'What is a good CoWork pattern for writing tasks (e.g., blog posts, emails)?', option_a: 'Ask Claude to write the entire piece without any input', option_b: 'Share an outline or bullet points, have Claude draft a first version, then iteratively refine together', option_c: 'Only use Claude for spellchecking at the end', option_d: 'Do not use Claude for writing tasks', correct_option: 'b', explanation: "Collaborative writing works best when you provide structure/outline, Claude drafts, and you refine together — combining your domain knowledge with Claude's writing ability." },
    { question: 'Why is the Claude Desktop App particularly useful for developers?', option_a: 'It comes with a built-in code editor', option_b: 'It enables local file system access and MCP server connections — letting Claude read, write, and interact with your actual project files', option_c: 'It automatically pushes code to GitHub', option_d: 'It runs code 10x faster than the web version', correct_option: 'b', explanation: 'The Desktop App allows Claude to interact with your local development environment — reading files, running tests, and using MCP-connected tools without copy-pasting.' },
    { question: 'What does using Claude for "meeting notes" in a CoWork context involve?', option_a: 'Claude attending the meeting in person', option_b: 'Pasting a meeting transcript into Claude and asking it to extract action items, decisions, and next steps', option_c: 'Claude automatically joining Zoom calls', option_d: "Scheduling meetings on Claude's behalf", correct_option: 'b', explanation: "A common CoWork pattern is pasting meeting transcripts into Claude to get structured summaries, decisions, and action items in seconds." },
    { question: "What is a 'multi-step task chain' in the Claude CoWork context?", option_a: 'Running multiple Claude accounts simultaneously', option_b: 'A sequence of related prompts where each step builds on the previous Claude output to complete a complex workflow end-to-end', option_c: 'A way to connect multiple Claude Desktop Apps', option_d: 'A billing plan for heavy users', correct_option: 'b', explanation: 'Task chaining involves a sequence of prompts — research → outline → draft → edit → format — where each Claude response feeds the next step.' },
    { question: "How does Claude Desktop App's ability to use local tools improve CoWork?", option_a: 'It makes Claude run faster by using local GPU', option_b: 'Claude can read your actual project files, run commands, check errors, and interact with local databases directly', option_c: 'Local tools allow Claude to access the internet faster', option_d: 'It removes the need for an internet connection', correct_option: 'b', explanation: 'Local tool access means Claude can directly engage with your real working environment — not just abstract code snippets.' },
    { question: 'What is the benefit of using Claude for code review in a CoWork workflow?', option_a: 'Claude writes the PR description automatically', option_b: 'Claude provides an instant, detailed second opinion on code quality, logic errors, security vulnerabilities, and style improvements', option_c: 'Claude auto-merges pull requests', option_d: 'Claude runs CI/CD pipelines', correct_option: 'b', explanation: "Claude acts as an on-demand expert code reviewer, catching issues, suggesting improvements, and explaining trade-offs — available 24/7 without scheduling a review." },
    { question: 'What makes Claude an effective "rubber duck debugger"?', option_a: 'Claude is waterproof', option_b: 'Explaining code issues to Claude forces you to articulate the problem clearly, and Claude often identifies the root cause in the explanation itself', option_c: 'Claude only answers yes/no questions about code', option_d: 'Claude produces rubber duck sound effects', correct_option: 'b', explanation: "Claude is an active rubber duck — it listens and usually identifies the bug you're describing, while you explain it." },
    { question: 'In a CoWork session, how should you handle a wrong answer from Claude?', option_a: 'Accept it as the truth and move on', option_b: 'Point out the error specifically, provide the correct information, and ask Claude to revise', option_c: 'Start a completely new conversation', option_d: 'Report Claude to Anthropic', correct_option: 'b', explanation: "Claude responds well to specific corrections — pointing out the error and providing the right answer allows it to revise accurately in the same conversation." },
    { question: "What is a 'context dump' technique in Claude CoWork?", option_a: 'Deleting all past conversation context', option_b: 'Pasting all relevant background information (requirements, existing code, constraints) at the start of a session so Claude has full context before answering', option_c: 'Asking Claude to summarize all past sessions', option_d: 'A memory management technique in the Claude API', correct_option: 'b', explanation: "A context dump gives Claude everything it needs upfront — requirements, constraints, existing code, examples — ensuring high-quality, relevant responses from the start." },
    { question: 'What type of work is Claude CoWork NOT ideal for?', option_a: 'Writing and editing documents', option_b: 'Performing physical actions in the real world (operating machinery, manual tasks)', option_c: 'Pair programming', option_d: 'Research and data analysis', correct_option: 'b', explanation: "Claude is a text-based AI — it excels at knowledge work but cannot perform physical or mechanical actions in the real world." },
    { question: 'What is one key best practice when using Claude for long CoWork sessions?', option_a: 'Never use more than 10 messages per session', option_b: "Periodically summarize the current state and goals to keep Claude's focus sharp as the conversation grows longer", option_c: 'Always start a new chat after 30 minutes', option_d: 'Use only single-word prompts to save tokens', correct_option: 'b', explanation: "As conversations get longer, periodic summaries help Claude stay focused on the core goal and prevent context drift in complex, multi-hour sessions." },
  ],
  'Extended Thinking & Research Mode': [
    { question: "What is Claude's 'Extended Thinking' feature?", option_a: 'A mode that makes Claude responses longer', option_b: "A capability where Claude exposes its internal step-by-step reasoning process before delivering the final answer", option_c: 'A feature that extends your subscription', option_d: 'An auto-scroll feature for long responses', correct_option: 'b', explanation: "Extended Thinking shows Claude's detailed internal reasoning process — allowing it to work through complex problems more carefully before committing to an answer." },
    { question: 'On which Claude plan is Extended Thinking available?', option_a: 'Free tier only', option_b: 'Claude Pro and higher (or via API with supported models)', option_c: 'All plans including free', option_d: 'Only the Team Enterprise plan', correct_option: 'b', explanation: 'Extended Thinking is available on Claude Pro and higher plans, and through the Anthropic API with Claude models that support the thinking feature.' },
    { question: 'What types of tasks benefit most from Extended Thinking?', option_a: 'Simple one-word answers', option_b: 'Complex math proofs, multi-step coding challenges, advanced logical reasoning, and nuanced analysis', option_c: 'Translating single sentences', option_d: 'Generating short email subject lines', correct_option: 'b', explanation: 'Extended Thinking is most valuable for tasks requiring deep reasoning — complex math, multi-file code architecture, legal analysis, and strategic problem-solving.' },
    { question: "What does Claude's 'thinking trace' show you?", option_a: 'A log of API calls made during the session', option_b: 'The step-by-step internal reasoning Claude went through before producing its final answer', option_c: 'A list of sources Claude referenced', option_d: 'The raw model weights used', correct_option: 'b', explanation: "The thinking trace is Claude's visible scratchpad — showing intermediate steps, hypothesis testing, self-correction, and reasoning paths leading to the final output." },
    { question: 'How does Extended Thinking help with code generation?', option_a: 'It makes code run faster', option_b: 'Claude can plan the architecture, check for edge cases, trace through logic, and self-correct before showing you the final code', option_c: 'It adds comments automatically', option_d: 'It formats code with proper indentation', correct_option: 'b', explanation: 'Extended Thinking gives Claude time to analyze the full problem space, design the solution architecture, and catch logical errors before generating final code.' },
    { question: "What is Claude's 'Research Mode'?", option_a: "A mode that disables all of Claude's knowledge", option_b: "A deep research capability where Claude conducts multi-source web searches, synthesizes results, and generates comprehensive research reports", option_c: 'A way to browse academic papers only', option_d: 'A Claude API feature for batch data processing', correct_option: 'b', explanation: 'Research Mode enables Claude to perform web searches, cross-reference multiple sources, evaluate reliability, and synthesize findings into structured reports.' },
    { question: 'When should you use Research Mode instead of standard Claude?', option_a: 'For any question about history', option_b: "When you need comprehensive, up-to-date analysis that combines Claude's reasoning with real-time web information and multiple sources", option_c: 'For creative writing tasks', option_d: 'When you want shorter responses', correct_option: 'b', explanation: 'Research Mode is ideal for in-depth investigative tasks — market research, technical deep-dives, competitive analysis — where breadth and currency of information matter.' },
    { question: "Does Claude's thinking trace count towards your context window usage?", option_a: 'No, it is separate from the context window', option_b: 'Yes, the thinking trace uses tokens from the context window, so very long traces can be expensive', option_c: 'Thinking traces are processed on a separate server', option_d: 'Thinking traces use a fixed 1000-token allocation', correct_option: 'b', explanation: "Claude's extended thinking tokens do consume part of the context window. Extended reasoning on very complex tasks can use substantial tokens." },
    { question: "How can you verify Claude's Research Mode results?", option_a: 'You cannot verify AI-generated research', option_b: 'Claude provides citations and source links — you should click through to verify key claims from primary sources', option_c: 'Claude sends the sources to your email', option_d: 'All Research Mode results are 100% accurate', correct_option: 'b', explanation: 'Research Mode provides source citations — always verify critical claims from the original sources, as Claude may still occasionally miss nuances.' },
    { question: 'What is the main trade-off of enabling Extended Thinking?', option_a: 'Claude becomes less intelligent', option_b: 'Response time is longer (Claude takes more time to reason), and it uses more tokens/cost', option_c: 'Extended Thinking reduces response quality', option_d: 'It limits Claude to technical topics only', correct_option: 'b', explanation: 'Extended Thinking takes more time and uses more computational resources — the trade-off is speed for depth and accuracy on complex problems.' },
    { question: 'How does Research Mode handle conflicting information from different sources?', option_a: 'It always picks the first source', option_b: 'Claude evaluates source credibility and notes contradictions, often presenting multiple perspectives with caveats', option_c: 'It asks you to pick the right answer', option_d: 'Research Mode only uses one source per query', correct_option: 'b', explanation: 'Claude assesses source quality and conflicting data, surfacing disagreements and noting uncertainty rather than hiding contradictions.' },
    { question: 'Can Extended Thinking be combined with tool use (web search, code execution)?', option_a: 'No, Extended Thinking works in isolation only', option_b: 'Yes, Claude can use Extended Thinking alongside tools — thinking through how to use each tool, evaluating results, and planning next steps', option_c: 'Only in the Enterprise API tier', option_d: 'Tool use disables Extended Thinking', correct_option: 'b', explanation: 'Extended Thinking + tool use is a powerful combination — Claude reasons about what tools to use, evaluates results, and plans follow-up actions in a coherent workflow.' },
    { question: 'What is a "token budget" in the context of Extended Thinking?', option_a: 'The monthly cost cap for your Claude subscription', option_b: 'A configurable limit (via API) on how many thinking tokens Claude can use, controlling depth vs. cost', option_c: 'A way to pre-pay for tokens', option_d: 'The number of words in a single response', correct_option: 'b', explanation: 'Via the API, you can set a thinking token budget — lower for fast, cheaper responses; higher for deep, thorough reasoning on complex tasks.' },
    { question: "Does Claude's Research Mode replace a human researcher?", option_a: 'Yes, it is 100% accurate and complete', option_b: 'No — it is a powerful research assistant that accelerates the process, but human judgment is still needed to verify and apply findings', option_c: 'Yes, for all academic papers', option_d: 'No, it can only search Wikipedia', correct_option: 'b', explanation: "Research Mode is an accelerant, not a replacement — it compresses hours of research into minutes, but human expertise is still needed to validate and contextualize results." },
    { question: "What happens when Claude's Extended Thinking encounters a contradiction in its own reasoning?", option_a: 'It stops and asks you to resolve it', option_b: 'Claude continues reasoning, may revise its earlier conclusions, and often notes the contradiction explicitly in its answer', option_c: 'The response is automatically deleted', option_d: 'Claude repeats the question back to you', correct_option: 'b', explanation: "Extended Thinking shows Claude's self-correction process — it may change direction mid-thinking when it detects an error, producing a more accurate final answer." },
  ],
  'Claude Code': [
    { question: 'What is Claude Code?', option_a: 'A VS Code color theme', option_b: "Anthropic's official command-line interface (CLI) agent that runs in your local terminal and interacts directly with your project files", option_c: 'A JavaScript code formatter', option_d: 'A web-based code playground inside Claude.ai', correct_option: 'b', explanation: 'Claude Code is an agentic CLI tool by Anthropic that operates inside your local terminal, giving Claude direct access to your codebase, file system, and development tools.' },
    { question: 'How do you install Claude Code?', option_a: 'Download it from the App Store', option_b: 'Run `npm install -g @anthropic-ai/claude-code` in your terminal', option_c: 'Install it as a VS Code extension', option_d: 'Sign up on the Claude Code website', correct_option: 'b', explanation: 'Claude Code is installed globally via npm with `npm install -g @anthropic-ai/claude-code`, then authenticated with your Anthropic API key.' },
    { question: 'What command launches Claude Code in your project directory?', option_a: 'start claude', option_b: 'claude', option_c: 'anthropic run', option_d: 'npx claude-ai', correct_option: 'b', explanation: 'After installation, running `claude` in your terminal from any project directory starts the Claude Code interactive session.' },
    { question: "What does Claude Code's safe mode protect against?", option_a: 'Syntax errors', option_b: 'Unauthorized or destructive terminal commands — Claude asks for explicit permission before running potentially risky operations', option_c: 'Accidental file formatting changes', option_d: 'Exceeding your monthly token limit', correct_option: 'b', explanation: "Claude Code's permission system requires your approval before it runs shell commands, preventing accidental destructive operations like deleting files." },
    { question: 'How does Claude Code access your project files?', option_a: 'It downloads them from GitHub', option_b: 'It reads files directly from your local file system in the current directory where you launched it', option_c: 'It requires you to paste the code into the terminal', option_d: 'It accesses files via an S3 bucket', correct_option: 'b', explanation: 'Claude Code reads, writes, and modifies your actual local files — it operates in your current working directory with direct file system access.' },
    { question: 'Can Claude Code run terminal commands like `npm test` or `git commit`?', option_a: 'No, Claude Code is read-only', option_b: 'Yes, with your approval Claude Code can run shell commands, tests, git operations, and other CLI tools', option_c: 'Only `git` commands are supported', option_d: 'Commands can only be run in sandbox environments', correct_option: 'b', explanation: 'Claude Code can execute terminal commands — npm, git, pytest, make, and more — with permission prompts to ensure you approve each action.' },
    { question: 'How does Claude Code integrate with VS Code?', option_a: 'It replaces VS Code', option_b: 'Via the Claude extension in VS Code, which lets you open Claude Code sessions linked to your current workspace', option_c: 'VS Code integration is not supported', option_d: 'By running as a background VS Code plugin automatically', correct_option: 'b', explanation: 'The official Claude VS Code extension creates seamless integration — you can launch Claude Code sessions from within VS Code with full project context.' },
    { question: "What is Claude Code's `/init` command used for?", option_a: 'Initializing a new git repository', option_b: 'Generating a CLAUDE.md file that describes your project structure and conventions so Claude understands your codebase', option_c: 'Installing project dependencies', option_d: 'Creating a new Claude Code profile', correct_option: 'b', explanation: '`/init` creates a CLAUDE.md file — a project context document that tells Claude about your tech stack, conventions, and important files for future sessions.' },
    { question: "What is the CLAUDE.md file in a Claude Code project?", option_a: 'A markdown-formatted changelog', option_b: "A special file read by Claude Code at startup that describes the project's structure, tech stack, and important conventions", option_c: 'A license file for Claude', option_d: 'A Claude prompt template for documentation generation', correct_option: 'b', explanation: 'CLAUDE.md is the project memory file — Claude Code reads it at the start of every session so it understands your project without you needing to re-explain it.' },
    { question: 'What is a key difference between Claude Code and GitHub Copilot?', option_a: 'Copilot is better at everything', option_b: 'Claude Code operates as a full terminal agent with file system access and command execution; Copilot is primarily an in-editor code completion tool', option_c: 'Claude Code only works for Python', option_d: 'GitHub Copilot can access the terminal', correct_option: 'b', explanation: "GitHub Copilot excels at inline code suggestions within an editor; Claude Code is a full agentic tool that can autonomously plan, write, test, and commit code changes." },
    { question: "What does the `/compact` command do in Claude Code?", option_a: 'Compresses your project files', option_b: 'Summarizes the current conversation history to free up context window space for longer sessions', option_c: 'Formats all code in the project', option_d: 'Removes unused npm packages', correct_option: 'b', explanation: '`/compact` compresses the conversation history by summarizing it, allowing you to continue long coding sessions without hitting context window limits.' },
    { question: 'How do you tell Claude Code to work on a specific file?', option_a: 'Email the file to Claude', option_b: 'Reference the file path directly in your prompt — e.g., "Refactor the auth logic in src/middleware/auth.ts"', option_c: 'Drag and drop the file into the terminal', option_d: 'Claude Code can only work on the entire project, not individual files', correct_option: 'b', explanation: 'You can reference specific files by path in your Claude Code prompts — Claude will read those files and focus its changes accordingly.' },
    { question: 'What authentication is required to use Claude Code?', option_a: 'A GitHub token', option_b: 'An Anthropic API key (or Claude Max/Pro subscription authentication)', option_c: 'A Google OAuth login', option_d: 'A corporate license from Anthropic', correct_option: 'b', explanation: 'Claude Code requires authentication with an Anthropic API key or via Claude Max subscription to access the Claude models powering the CLI.' },
    { question: "What is Claude Code's project memory feature?", option_a: 'A database for storing code backups', option_b: "A way to save key project facts and conventions to Claude's persistent memory (CLAUDE.md) so they persist across sessions", option_c: 'A RAM optimization feature', option_d: 'A feature for memorizing user preferences', correct_option: 'b', explanation: "Project memory in Claude Code (via CLAUDE.md) stores critical project context that persists between sessions, so Claude doesn't need to re-learn your project structure each time." },
    { question: 'What makes Claude Code particularly powerful for refactoring large codebases?', option_a: 'It can only refactor one line at a time', option_b: 'Claude can read multiple files simultaneously, understand cross-file dependencies, and implement consistent refactoring changes across the entire codebase', option_c: 'Refactoring requires manual approval for each file', option_d: 'Claude Code cannot handle projects larger than 10 files', correct_option: 'b', explanation: 'Claude Code can load an entire project context, trace dependencies across files, and make coordinated, consistent refactoring changes across multiple files in one session.' },
  ],
  'MCP — Model Context Protocol': [
    { question: 'What does MCP stand for?', option_a: 'Machine Code Protocol', option_b: 'Model Context Protocol', option_c: 'Multi-Cloud Platform', option_d: 'Memory Control Process', correct_option: 'b', explanation: 'MCP stands for Model Context Protocol — an open standard developed by Anthropic for connecting AI models to external data sources and tools.' },
    { question: 'What problem does MCP solve in AI development?', option_a: 'It speeds up AI model training', option_b: "It provides a unified, standardized protocol for AI models to connect to external data sources and tools — replacing bespoke, one-off integrations", option_c: 'It reduces the size of AI models', option_d: 'It encrypts AI outputs', correct_option: 'b', explanation: 'Before MCP, every AI-tool integration required custom code. MCP provides a standard protocol so any tool can be connected to any MCP-compatible AI client.' },
    { question: 'In MCP architecture, what is the "MCP Host"?', option_a: 'A cloud server run by Anthropic', option_b: 'The application where the AI model runs (e.g., Claude Desktop App or Claude Code) that connects to MCP servers', option_c: 'The database being queried', option_d: 'A physical computer running the MCP protocol', correct_option: 'b', explanation: "The MCP Host is the AI application (like Claude Desktop) that coordinates connections between the AI model and one or more MCP Servers." },
    { question: 'What is an "MCP Server"?', option_a: 'A powerful GPU server running the AI model', option_b: 'A lightweight process that exposes specific resources, tools, or data sources to the AI via the MCP protocol', option_c: 'A web server hosting the Claude.ai website', option_d: 'A server that stores your conversation history', correct_option: 'b', explanation: "An MCP Server is a small program that bridges a data source or tool (a filesystem, database, API) and the AI client using the standardized MCP protocol." },
    { question: 'What file do you edit to configure MCP servers in Claude Desktop App?', option_a: 'settings.json', option_b: 'claude_desktop_config.json', option_c: '.env.claude', option_d: 'mcp_servers.yaml', correct_option: 'b', explanation: "Claude Desktop reads its MCP server configuration from `claude_desktop_config.json`, where you define each server's executable, arguments, and environment variables." },
    { question: "What are the three main concepts MCP Servers can expose?", option_a: 'Files, Images, and Videos', option_b: 'Resources (data), Tools (actions), and Prompts (reusable prompt templates)', option_c: 'APIs, Webhooks, and Databases only', option_d: 'Functions, Classes, and Modules', correct_option: 'b', explanation: 'MCP Servers expose: Resources (readable data/content), Tools (callable functions/actions), and Prompts (pre-built prompt templates for common tasks).' },
    { question: 'How does the filesystem MCP server work?', option_a: 'It uploads your files to the cloud', option_b: 'It exposes your local file system to Claude, allowing it to read, write, list, and search files within allowed directories', option_c: 'It syncs files to Google Drive', option_d: 'It compresses files automatically', correct_option: 'b', explanation: 'The filesystem MCP server gives Claude controlled read/write access to your local directories — enabling it to read code, write documents, and manage files.' },
    { question: "What is the `stdio` transport in MCP?", option_a: 'A database streaming protocol', option_b: 'A communication method where the MCP Host talks to the MCP Server via standard input/output (stdin/stdout) — used for local servers', option_c: 'A wireless transmission standard', option_d: 'An HTTP API standard', correct_option: 'b', explanation: 'The `stdio` transport runs the MCP Server as a subprocess and communicates via stdin/stdout — the most common approach for local MCP integrations.' },
    { question: 'What is a "remote MCP server" using SSE transport?', option_a: 'A server hosted in outer space', option_b: 'An MCP server running on a remote machine, communicating via Server-Sent Events (HTTP streaming) — used for cloud-hosted data sources', option_c: 'A server with extra long response times', option_d: 'A server running inside a Docker container locally', correct_option: 'b', explanation: "SSE (Server-Sent Events) transport allows MCP Servers to run remotely (in the cloud) and stream responses to the AI client over HTTP." },
    { question: "What is the 'Brave Search' MCP server used for?", option_a: 'Searching for restaurants', option_b: "Giving Claude access to Brave's web search API — allowing Claude to retrieve real-time web search results during a conversation", option_c: 'Finding files in your file system', option_d: 'Searching your email inbox', correct_option: 'b', explanation: "The Brave Search MCP server connects Claude to the Brave Search API, enabling real-time web search results as part of Claude's response generation." },
    { question: 'What is the security model for MCP servers?', option_a: 'MCP servers have unrestricted access to everything', option_b: "MCP servers only have access to the resources you explicitly configure and authorize — you control what Claude can access", option_c: 'Security is handled entirely by Anthropic', option_d: 'All MCP servers require two-factor authentication', correct_option: 'b', explanation: 'MCP servers operate with a least-privilege model — you explicitly configure what resources and actions each server can expose, controlling Claude\'s access scope.' },
    { question: 'What is the GitHub MCP server used for?', option_a: 'Hosting websites on GitHub Pages', option_b: 'Allowing Claude to interact with GitHub repositories — reading code, creating issues, opening PRs, and more', option_c: 'Cloning repositories to a backup drive', option_d: 'Translating code between programming languages', correct_option: 'b', explanation: "The GitHub MCP server lets Claude interact with GitHub API — reading repos, creating issues, making PRs, reviewing code — all within the Claude interface." },
    { question: "What makes MCP superior to Claude's built-in Connectors for developers?", option_a: 'Built-in Connectors are more secure', option_b: 'MCP is fully extensible and open-source — developers can build custom MCP servers for any data source or API, not just pre-approved integrations', option_c: 'Connectors support more third-party tools', option_d: 'MCP does not require API keys', correct_option: 'b', explanation: 'MCP is an open standard — anyone can write an MCP server for any system (internal databases, proprietary APIs, custom tools), giving developers unlimited extensibility.' },
    { question: 'How do you tell Claude to use a specific MCP tool during a conversation?', option_a: 'Write a special SQL query', option_b: "Describe the task naturally — Claude automatically determines when to invoke available MCP tools based on the conversation context", option_c: 'Type /use-mcp followed by the tool name', option_d: 'MCP tools must be called manually from the terminal', correct_option: 'b', explanation: "Claude recognizes when an MCP tool is the right resource for the task and calls it autonomously — you just describe what you need in natural language." },
    { question: 'What is the Postgres MCP server used for?', option_a: 'Hosting a website using PostgreSQL', option_b: "Giving Claude direct query access to a PostgreSQL database — allowing it to read schemas, run SELECT queries, and analyze data", option_c: 'Backing up your PostgreSQL database', option_d: 'Generating fake data for testing', correct_option: 'b', explanation: 'The Postgres MCP server connects Claude to your PostgreSQL instance, letting it inspect schemas and run read-only queries to answer questions about your data.' },
  ],
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log('🔍 Finding course: master-claude-ai-zero-to-pro')

  const { data: course, error: courseError } = await db
    .from('courses')
    .select('id, title, slug')
    .eq('slug', 'master-claude-ai-zero-to-pro')
    .single()

  if (courseError || !course) {
    console.error('❌ Course not found:', courseError)
    process.exit(1)
  }
  console.log(`✅ Found course: ${course.title} (${course.id})`)

  const { data: modules, error: moduleError } = await db
    .from('modules')
    .select('id, title, order_index')
    .eq('course_id', course.id)
    .order('order_index')

  if (moduleError || !modules || modules.length === 0) {
    console.error('❌ Modules not found:', moduleError)
    process.exit(1)
  }
  console.log(`✅ Found ${modules.length} modules`)

  // 1. Update module descriptions
  console.log('\n📝 Updating module descriptions...')
  for (const mod of modules) {
    const introData = MODULE_INTROS[mod.title]
    if (!introData) { console.warn(`  ⚠️  No intro data for: "${mod.title}"`); continue }
    const { error } = await db.from('modules').update({ description: JSON.stringify(introData) }).eq('id', mod.id)
    if (error) { console.error(`  ❌ Failed: "${mod.title}":`, error.message) }
    else { console.log(`  ✅ Updated: ${mod.title}`) }
  }

  // 2. Delete existing quizzes
  console.log('\n🗑️  Deleting existing quizzes...')
  const moduleIds = modules.map(m => m.id)
  const { error: deleteError } = await db.from('quizzes').delete().in('module_id', moduleIds)
  if (deleteError) { console.error('  ❌ Failed to delete quizzes:', deleteError.message); process.exit(1) }
  console.log(`  ✅ Deleted existing quizzes for ${modules.length} modules`)

  // 3. Insert 15 questions per module
  console.log('\n🧠 Inserting 15 quiz questions per module...')
  let totalInserted = 0
  for (const mod of modules) {
    const questions = MODULE_QUIZZES[mod.title]
    if (!questions) { console.warn(`  ⚠️  No questions for: "${mod.title}"`); continue }

    const rows = questions.map((q, idx) => ({
      module_id: mod.id,
      question: q.question,
      option_a: q.option_a,
      option_b: q.option_b,
      option_c: q.option_c,
      option_d: q.option_d,
      correct_option: q.correct_option,
      explanation: q.explanation,
      order_index: idx + 1,
    }))

    const { error: insertError } = await db.from('quizzes').insert(rows)
    if (insertError) { console.error(`  ❌ Failed for "${mod.title}":`, insertError.message) }
    else { totalInserted += questions.length; console.log(`  ✅ ${questions.length} questions for: ${mod.title}`) }
  }

  console.log(`\n✨ Done! Total questions inserted: ${totalInserted}`)
  console.log(`   Expected: ${modules.length * 15} (${modules.length} modules × 15 questions)`)
  if (totalInserted === modules.length * 15) { console.log('   🎉 All questions inserted successfully!') }
  else { console.warn('   ⚠️  Some questions may be missing. Check errors above.') }
}

main().catch(err => { console.error('Fatal error:', err); process.exit(1) })
