import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.join(process.cwd(), '.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const flashcardData = {
  "titleCard": {
    "headline": "Master Claude AI — Zero to Pro",
    "subheadline": "Master Anthropic's Claude, prompt engineering, Projects, Artifacts, MCP tools, and Claude Code.",
    "emoji": "🤖",
    "imageKeyword": "code"
  },
  "courseOverview": {
    "welcome": "Welcome! In this course, you'll master Claude, Anthropic's state-of-the-art AI assistant. We have divided the course into 10 modules, covering everything from prompt engineering to local terminal agents like Claude Code. 🚀",
    "modules": [
      {
        "title": "What Is Claude & Why It Matters",
        "description": "Understand Claude's unique features, reasoning capability, and how it compares to other AIs.",
        "emoji": "💡"
      },
      {
        "title": "The Claude Interface & Core Features",
        "description": "Navigate the web chat interface, manage chats, and customize your experience.",
        "emoji": "🖥️"
      },
      {
        "title": "Prompt Engineering for Claude",
        "description": "Write high-quality prompts optimized for Claude's XML tags and direct instruction.",
        "emoji": "✍️"
      },
      {
        "title": "Claude Artifacts",
        "description": "Use the side-by-side workspace to build apps, write documents, and run code.",
        "emoji": "📦"
      },
      {
        "title": "Claude Projects",
        "description": "Create custom contexts, knowledge bases, and custom system instructions.",
        "emoji": "📂"
      },
      {
        "title": "Claude Skills & Connectors",
        "description": "Extend Claude with external integrations and build custom interactive skills.",
        "emoji": "🔌"
      },
      {
        "title": "Claude CoWork",
        "description": "Learn to use Claude as a collaborative co-worker in your daily dev workflows.",
        "emoji": "👥"
      },
      {
        "title": "Extended Thinking & Research Mode",
        "description": "Leverage Claude's deep reasoning and search capabilities for complex research.",
        "emoji": "🔍"
      },
      {
        "title": "Claude Code",
        "description": "Use Claude's official CLI command-line agent to build and refactor local codebases.",
        "emoji": "💻"
      },
      {
        "title": "MCP — Model Context Protocol",
        "description": "Connect Claude to any data source, tool, server, or API securely and seamlessly.",
        "emoji": "⚙️"
      }
    ]
  },
  "glossary": [
    {
      "term": "Prompt Engineering",
      "definition": "The practice of structuring text inputs (prompts) to get the most accurate, safe, and helpful responses from Claude.",
      "example": "Using XML tags like <context> or <instructions> helps Claude separate different parts of your prompt.",
      "emoji": "✍️",
      "imageKeyword": "code"
    },
    {
      "term": "Artifacts",
      "definition": "A dedicated workspace that opens on the right side of the screen, allowing you to view and interact with code, websites, SVGs, or documents generated by Claude.",
      "example": "When Claude builds an interactive React dashboard, it renders directly in the Artifacts panel.",
      "emoji": "📦",
      "imageKeyword": "design"
    },
    {
      "term": "Projects",
      "definition": "A feature in Claude Pro/Team that lets you bundle documents, codebase files, and custom system instructions into a single shared workspace.",
      "example": "Uploading your team's style guide into a Claude Project keeps all copy aligned to the brand tone.",
      "emoji": "📂",
      "imageKeyword": "product"
    },
    {
      "term": "Claude Code",
      "definition": "An official command-line interface (CLI) tool that runs Claude directly in your local terminal, with permissions to edit files, run tests, and execute git commands.",
      "example": "Running 'claude dev' in your project root lets Claude find and fix compiler bugs automatically.",
      "emoji": "💻",
      "imageKeyword": "terminal"
    },
    {
      "term": "Model Context Protocol (MCP)",
      "definition": "An open standard that enables AI models to connect securely to local or remote data sources, development tools, and APIs.",
      "example": "Using an MCP server to let Claude query your local SQLite database directly from chat.",
      "emoji": "🔌",
      "imageKeyword": "server"
    }
  ],
  "glossaryQuiz": [
    {
      "question": "Which Claude feature provides a side-by-side workspace to view and interact with generated code, websites, or docs?",
      "options": ["Projects", "Artifacts", "Claude Code", "System Prompts"],
      "correctIndex": 1,
      "term": "Artifacts"
    },
    {
      "question": "What is the primary purpose of 'Projects' in Claude.ai?",
      "options": [
        "To compile code into an executable application.",
        "To purchase API credits and manage subscriptions.",
        "To group documents, files, and custom instructions for a specific task.",
        "To run Claude inside your local VS Code terminal."
      ],
      "correctIndex": 2,
      "term": "Projects"
    },
    {
      "question": "What is Claude Code?",
      "options": [
        "A coding theme for VS Code.",
        "A local command-line agent developed by Anthropic to interact with your codebase.",
        "Anthropic's proprietary programming language.",
        "The web-based compiler used inside Artifacts."
      ],
      "correctIndex": 1,
      "term": "Claude Code"
    },
    {
      "question": "What does the Model Context Protocol (MCP) do?",
      "options": [
        "It acts as a secure firewall that blocks external APIs.",
        "It enables Claude to connect to databases, tools, and servers via an open standard.",
        "It is a formatting standard for writing system prompts.",
        "It compiles Python script files into Javascript."
      ],
      "correctIndex": 1,
      "term": "Model Context Protocol (MCP)"
    }
  ],
  "courseMap": {
    "overview": "You will watch expert-curated tutorial videos, learn prompt engineering, configure local projects and connectors, test your knowledge, and earn your course certificate.",
    "steps": [
      "Master the web UI (Artifacts & Projects)",
      "Learn prompt engineering XML structures",
      "Build local terminal workflows with Claude Code & MCP",
      "Pass all module quizzes & claim your certificate"
    ]
  }
}

async function run() {
  const slug = 'master-claude-ai-zero-to-pro'
  
  console.log(`Searching for course with slug: ${slug}...`)
  
  const { data: course, error: fetchError } = await supabase
    .from('courses')
    .select('id, title, flashcard_data')
    .eq('slug', slug)
    .single()
    
  if (fetchError) {
    console.error('Error fetching course:', fetchError)
    process.exit(1)
  }
  
  console.log(`Found course: ${course.title} (ID: ${course.id})`)
  console.log('Current flashcard_data:', JSON.stringify(course.flashcard_data, null, 2))
  
  console.log('Updating flashcard_data...')
  
  const { data: updatedCourse, error: updateError } = await supabase
    .from('courses')
    .update({ flashcard_data: flashcardData })
    .eq('id', course.id)
    .select()
    .single()
    
  if (updateError) {
    console.error('Error updating course flashcard_data:', updateError)
    process.exit(1)
  }
  
  console.log('Update successful!')
  console.log('Updated flashcard_data:', JSON.stringify(updatedCourse.flashcard_data, null, 2))
}

run().catch((err) => {
  console.error('Unexpected error:', err)
  process.exit(1)
})
